local config = {
    features = {
        autopairs = true,
        copilot = true,
    },
    diagnostics_virtual_text = true,
    diagnostics_level = "Hint",
    lsp_deps = {
        "bashls",
        "clangd",
        "neocmake",
        "cssls",
        "cssmodules_ls",
        "csharp_ls",
        "eslint",
        "html",
        "jsonls",
        "lua_ls",
        "pylsp",
        "tsserver",
        "vuels",
        "volar",
    },
    dap_deps = {
        "clang_format",
        "codelldb",
        "js",
        "prettier",
        "shfmt",
        "stylua",
        "vint",
    },
    treesitter_deps = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "css",
        "html",
        "javascript",
        "json",
        "latex",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "python",
        "regex",
        "rust",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "yaml",
    },
    null_ls_deps = {
        "black",
        "clang_format",
        "isort",
        "prettier",
        "selene",
        "shfmt",
        "stylua",
        "vint",
    },
}

return config
