require("keymap.plugins.autopairs")
require("keymap.plugins.barbar")
require("keymap.plugins.colorizer")
require("keymap.plugins.comment")
require("keymap.plugins.conform")
require("keymap.plugins.diffview")
require("keymap.plugins.lazy")
require("keymap.plugins.mason")
require("keymap.plugins.persistence")
require("keymap.plugins.smart-split")
require("keymap.plugins.snacks")
require("keymap.plugins.suda")
require("keymap.plugins.telescope")
require("keymap.plugins.todo-comment")
require("keymap.plugins.toggleterm")
require("keymap.plugins.yazi")

require("keymap.editor")
